// <auto-generated />
using HRDashboard.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRDashboard.DataAccess.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20260331111744_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("HRDashboard.Domain.Entities.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = "company-paks",
                            CompanyName = "Paks Logistic LLC",
                            Email = "dispatch@pakslogistic.com",
                            Name = "Paks Admin",
                            PasswordHash = "$2a$11$YXFM.cjpJGvSUQVoecy8fOFqb8n0iLyV1ALp0.1.YxZsNMJuGl.Qy",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = "company-paks",
                            CompanyName = "Paks Logistic LLC",
                            Email = "accounting@pakslogistic.com",
                            Name = "Paks Accounting",
                            PasswordHash = "$2a$11$xVuQG.4dpHibXlwVh6YnX.I9fDKs96dw6uPKh4NbDEih8FNAdVQXa",
                            Role = "accounting"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
