// <auto-generated />
using System;
using HRDashboard.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRDashboard.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317125709_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("HRDashboard.API.Models.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Applicants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = "company-paks",
                            Date = "07/22/23",
                            Equipment = "Van",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe",
                            Name = "John Doe",
                            Position = "Owner Operator",
                            Status = "Applied"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = "company-paks",
                            Date = "07/22/23",
                            Equipment = "Reefer",
                            FirstName = "Jane",
                            IsDeleted = false,
                            LastName = "Smith",
                            Name = "Jane Smith",
                            Position = "Company Driver",
                            Status = "Contacted"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = "company-paks",
                            Date = "07/22/23",
                            Equipment = "Flat Bed",
                            FirstName = "Mike",
                            IsDeleted = false,
                            LastName = "Johnson",
                            Name = "Mike Johnson",
                            Position = "Owner Operator",
                            Status = "Documents Sent"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = "company-paks",
                            Date = "07/23/23",
                            Equipment = "Van",
                            FirstName = "Sarah",
                            IsDeleted = false,
                            LastName = "Williams",
                            Name = "Sarah Williams",
                            Position = "Company Driver",
                            Status = "Applied"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = "company-paks",
                            Date = "07/23/23",
                            Equipment = "Reefer",
                            FirstName = "David",
                            IsDeleted = false,
                            LastName = "Brown",
                            Name = "David Brown",
                            Position = "Company Driver",
                            Status = "Contacted"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = "company-paks",
                            Date = "07/24/23",
                            Equipment = "Flat Bed",
                            FirstName = "Emily",
                            IsDeleted = false,
                            LastName = "Davis",
                            Name = "Emily Davis",
                            Position = "Owner Operator",
                            Status = "Documents Sent"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = "company-paks",
                            Date = "07/24/23",
                            Equipment = "Van",
                            FirstName = "Michael",
                            IsDeleted = false,
                            LastName = "Wilson",
                            Name = "Michael Wilson",
                            Position = "Owner Operator",
                            Status = "Applied"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = "company-paks",
                            Date = "07/25/23",
                            Equipment = "Van",
                            FirstName = "Jennifer",
                            IsDeleted = false,
                            LastName = "Martinez",
                            Name = "Jennifer Martinez",
                            Position = "Company Driver",
                            Status = "Contacted"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = "company-paks",
                            Date = "07/25/23",
                            Equipment = "Flat Bed",
                            FirstName = "Robert",
                            IsDeleted = false,
                            LastName = "Taylor",
                            Name = "Robert Taylor",
                            Position = "Company Driver",
                            Status = "Applied"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = "company-paks",
                            Date = "07/26/23",
                            Equipment = "Reefer",
                            FirstName = "Jessica",
                            IsDeleted = false,
                            LastName = "Anderson",
                            Name = "Jessica Anderson",
                            Position = "Owner Operator",
                            Status = "Documents Sent"
                        });
                });

            modelBuilder.Entity("HRDashboard.API.Models.Application", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dislike")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DrivingExperience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DrivingRecord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DrugTest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Felonies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OnRoad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OvernightPark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousCompany")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonForLeaving")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryExpectation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecuringUnloading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialConsideration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkedReefer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("HRDashboard.API.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("HRDashboard.API.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = "company-paks",
                            Date = "01/15/2024",
                            DriverStatus = "Ready",
                            EmploymentStatus = "Working",
                            Equipment = "Van",
                            FirstName = "John",
                            IsEmployee = true,
                            LastName = "Smith",
                            Name = "John Smith",
                            PaymentType = "percent",
                            Position = "Owner Operator",
                            Status = "Applied"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = "company-paks",
                            Date = "01/18/2024",
                            DriverStatus = "Not Ready",
                            EmploymentStatus = "Fired",
                            Equipment = "Reefer",
                            FirstName = "Maria",
                            IsEmployee = true,
                            LastName = "Garcia",
                            Name = "Maria Garcia",
                            PaymentType = "miles",
                            Position = "Company Driver",
                            Status = "Contacted"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = "company-paks",
                            Date = "01/20/2024",
                            DriverStatus = "Ready",
                            EmploymentStatus = "Working",
                            Equipment = "Van",
                            FirstName = "James",
                            IsEmployee = true,
                            LastName = "Wilson",
                            Name = "James Wilson",
                            PaymentType = "miles",
                            Position = "Company Driver",
                            Status = "Documents Sent"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = "company-paks",
                            Date = "01/22/2024",
                            DriverStatus = "Ready",
                            EmploymentStatus = "Working",
                            Equipment = "Reefer",
                            FirstName = "Patricia",
                            IsEmployee = true,
                            LastName = "Brown",
                            Name = "Patricia Brown",
                            PaymentType = "percent",
                            Position = "Owner Operator",
                            Status = "Applied"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = "company-paks",
                            Date = "01/25/2024",
                            DriverStatus = "Not Ready",
                            EmploymentStatus = "Working",
                            Equipment = "Flat Bed",
                            FirstName = "Robert",
                            IsEmployee = true,
                            LastName = "Jones",
                            Name = "Robert Jones",
                            PaymentType = "percent",
                            Position = "Company Driver",
                            Status = "Contacted"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = "company-paks",
                            Date = "02/01/2024",
                            DriverStatus = "Ready",
                            EmploymentStatus = "Working",
                            Equipment = "Van",
                            FirstName = "Linda",
                            IsEmployee = true,
                            LastName = "Davis",
                            Name = "Linda Davis",
                            PaymentType = "percent",
                            Position = "Owner Operator",
                            Status = "Documents Sent"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = "company-paks",
                            Date = "02/03/2024",
                            DriverStatus = "Ready",
                            EmploymentStatus = "Working",
                            Equipment = "Van",
                            FirstName = "Michael",
                            IsEmployee = true,
                            LastName = "Miller",
                            Name = "Michael Miller",
                            PaymentType = "miles",
                            Position = "Company Driver",
                            Status = "Applied"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = "company-paks",
                            Date = "02/05/2024",
                            DriverStatus = "Not Ready",
                            EmploymentStatus = "Fired",
                            Equipment = "Flat Bed",
                            FirstName = "Elizabeth",
                            IsEmployee = true,
                            LastName = "Martinez",
                            Name = "Elizabeth Martinez",
                            PaymentType = "miles",
                            Position = "Company Driver",
                            Status = "Contacted"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = "company-paks",
                            Date = "02/08/2024",
                            DriverStatus = "Ready",
                            EmploymentStatus = "Working",
                            Equipment = "Reefer",
                            FirstName = "William",
                            IsEmployee = true,
                            LastName = "Anderson",
                            Name = "William Anderson",
                            PaymentType = "percent",
                            Position = "Owner Operator",
                            Status = "Applied"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = "company-paks",
                            Date = "02/10/2024",
                            DriverStatus = "Ready",
                            EmploymentStatus = "Working",
                            Equipment = "Reefer",
                            FirstName = "Jennifer",
                            IsEmployee = true,
                            LastName = "Taylor",
                            Name = "Jennifer Taylor",
                            PaymentType = "miles",
                            Position = "Company Driver",
                            Status = "Documents Sent"
                        });
                });

            modelBuilder.Entity("HRDashboard.API.Models.SavedStatement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adjustment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdjustmentAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdjustmentReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrossAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Miles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Percent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RatePerMile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtotal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SavedStatements");
                });

            modelBuilder.Entity("HRDashboard.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = "company-paks",
                            CompanyName = "Paks Logistic LLC",
                            Email = "dispatch@pakslogistic.com",
                            Name = "Paks Admin",
                            PasswordHash = "$2a$11$qMhH9D/9ChooA9oa/ypZeeovCBIyMsSyzia4FxSyF.4NmDKRSkYDi",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = "company-paks",
                            CompanyName = "Paks Logistic LLC",
                            Email = "accounting@pakslogistic.com",
                            Name = "Paks Accounting",
                            PasswordHash = "$2a$11$4pMNHldxdgGbIsR767HKcuYlr3AgPf2FglCFWyRyHjAkeMVdBAAxi",
                            Role = "accounting"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
